### ISSUE TITLE
Incluir funcionalidad de intro.

### ISSUE THREAD

**Issue by renzoz** [renzoz/soft2#4]
Hay que permitir usar el intro como si fuera el boton de enviar.
Para ciclo 2.

**Comment by ricardosanzh** [comment]
Falta introducir la funcionalidad de la tecla intro que haga como "Enviar"
Tipo de problema: Diseño
Localización:
Menu_Alta_Coche.java, 
Menu_Consulta_Modelo.java,
Menu_Devolver.java,
Menu_Est_Tarifas.java,
Menu_Facturacion.java, 
Menu_Reserva.java

**Comment by ricardosanzh** [comment]
NO SE IMPLEMENTARA FINALMENTE, ELIMINAR DE TRACK DE DEFECTOS.
