### ISSUE TITLE
Lista de extras.

### ISSUE THREAD

**Issue by renzoz** [renzoz/soft2#5]
Incluir una lista de los extras disponibles en la base de datos.
Para ciclo 2.

**Comment by renzoz** [comment]
Tipo de defecto: Diseño.
Deteccion: 15 de noviembre.
Durante: Revision de codigo e integracion.
Solucionado: Movido a ciclo 2.
Localizacion: Clase de Extras.

**Comment by ricardosanzh** [comment]
SOLUCIONADO LO RELATIVO A LOS EXTRAS EN LA INTERFAZ.
