### ISSUE TITLE
Hacer otro jdialog en alta de coche.

### ISSUE THREAD

**Issue by renzoz** [renzoz/soft2#6]
Hacer un jdialog para informar que hay que reiniciar el programa para cargar los nuevos coches disponibles.

**Comment by ricardosanzh** [comment]
Hacer una ventana emergente que avise de que hay que reiniciar el programa para recargar los nuevos coches que se han introducido
Tipo de problema: Diseño
Fecha: 15/11/2015
Localización: Casos de pruebas
Localización:
Menu_Alta_Coche.java

**Comment by ricardosanzh** [comment]
SOLUCIONADO --> Solo avisa, no reinicia!!
