### ISSUE TITLE
Cambiar input de modelo a combobox

### ISSUE THREAD

**Issue by renzoz** [renzoz/soft2#7]
Cambiar en alquilar, reservar, consultar, establecer tarifas y facturacion (todo menos alta coches) que la entrada del modelo sea un combobox con la lista de modelos de coches existentes en la base de datos al iniciar el programa.
Tambien incluir un metodo que devuelva un array de los modelos de coche para la seleccion.

**Comment by ricardosanzh** [comment]
Cambiar el tipo de menu a ComboBox para que aparezca una lista de coches existentes que hay en la base de datos.

Tipo de problema: Diseño
Fecha: 15/11/2015
Localización: Casos de pruebas
Localización:
Menu_Alquilar.java, 
Menu_Consulta_Modelo.java,
Menu_Devolver.java,
Menu_Est_Tarifas.java,
Menu_Facturacion.java, 
Menu_Reserva.java

**Comment by ricardosanzh** [comment]
SOLUCIONADO
